In [2]:
import torch

## Tensor.scatter_函数

In [34]:
score = torch.arange(1,13).reshape((3,4))
score

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [36]:
index = torch.tensor([[0,1,2,1]])
index

tensor([[0, 1, 2, 1]])

In [37]:
mask = torch.zeros(score.shape,dtype=score.dtype)
mask

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [39]:
# dim=0
mask.scatter_(0, index, score)

tensor([[1, 0, 0, 0],
        [0, 2, 0, 4],
        [0, 0, 3, 0]])

In [40]:
# dim=1
mask.scatter_(1, index, score)

tensor([[1, 4, 3, 0],
        [0, 2, 0, 4],
        [0, 0, 3, 0]])