### torch.chunk

In [2]:
import torch

In [3]:
t_2 = torch.arange(24).reshape(4,6)
t_2.shape

torch.Size([4, 6])

In [4]:
t_2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [5]:
t1 = torch.chunk(input=t_2,chunks=2,dim=0)
t1

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]))

In [16]:
t1[0].shape

torch.Size([2, 6])

In [6]:
t2 = torch.chunk(t_2, 2, 1)
t2

(tensor([[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]]),
 tensor([[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]]))

In [17]:
t2[0].shape

torch.Size([4, 3])

In [8]:
t_3 = torch.arange(64).reshape(4,4,4)
t_3

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]])

In [9]:
t_31 = torch.chunk(t_3, 2, 0)
t_31

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]],
 
         [[16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31]]]),
 tensor([[[32, 33, 34, 35],
          [36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47]],
 
         [[48, 49, 50, 51],
          [52, 53, 54, 55],
          [56, 57, 58, 59],
          [60, 61, 62, 63]]]))

In [10]:
t_31[0].shape

torch.Size([2, 4, 4])

In [11]:
t_32 = torch.chunk(t_3, 2, 1)
t_32

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7]],
 
         [[16, 17, 18, 19],
          [20, 21, 22, 23]],
 
         [[32, 33, 34, 35],
          [36, 37, 38, 39]],
 
         [[48, 49, 50, 51],
          [52, 53, 54, 55]]]),
 tensor([[[ 8,  9, 10, 11],
          [12, 13, 14, 15]],
 
         [[24, 25, 26, 27],
          [28, 29, 30, 31]],
 
         [[40, 41, 42, 43],
          [44, 45, 46, 47]],
 
         [[56, 57, 58, 59],
          [60, 61, 62, 63]]]))

In [12]:
t_32[0].shape

torch.Size([4, 2, 4])

In [14]:
t_33 = torch.chunk(t_3, 3, 2)
t_33

(tensor([[[ 0,  1],
          [ 4,  5],
          [ 8,  9],
          [12, 13]],
 
         [[16, 17],
          [20, 21],
          [24, 25],
          [28, 29]],
 
         [[32, 33],
          [36, 37],
          [40, 41],
          [44, 45]],
 
         [[48, 49],
          [52, 53],
          [56, 57],
          [60, 61]]]),
 tensor([[[ 2,  3],
          [ 6,  7],
          [10, 11],
          [14, 15]],
 
         [[18, 19],
          [22, 23],
          [26, 27],
          [30, 31]],
 
         [[34, 35],
          [38, 39],
          [42, 43],
          [46, 47]],
 
         [[50, 51],
          [54, 55],
          [58, 59],
          [62, 63]]]))

In [15]:
t_33[0].shape

torch.Size([4, 4, 2])

In [39]:
t_4 = torch.arange(576).reshape(4,3,6,8)
t_4

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7],
          [  8,   9,  10,  11,  12,  13,  14,  15],
          [ 16,  17,  18,  19,  20,  21,  22,  23],
          [ 24,  25,  26,  27,  28,  29,  30,  31],
          [ 32,  33,  34,  35,  36,  37,  38,  39],
          [ 40,  41,  42,  43,  44,  45,  46,  47]],

         [[ 48,  49,  50,  51,  52,  53,  54,  55],
          [ 56,  57,  58,  59,  60,  61,  62,  63],
          [ 64,  65,  66,  67,  68,  69,  70,  71],
          [ 72,  73,  74,  75,  76,  77,  78,  79],
          [ 80,  81,  82,  83,  84,  85,  86,  87],
          [ 88,  89,  90,  91,  92,  93,  94,  95]],

         [[ 96,  97,  98,  99, 100, 101, 102, 103],
          [104, 105, 106, 107, 108, 109, 110, 111],
          [112, 113, 114, 115, 116, 117, 118, 119],
          [120, 121, 122, 123, 124, 125, 126, 127],
          [128, 129, 130, 131, 132, 133, 134, 135],
          [136, 137, 138, 139, 140, 141, 142, 143]]],


        [[[144, 145, 146, 147, 148, 149, 150, 151],
    

In [40]:
t_4.shape

torch.Size([4, 3, 6, 8])

In [41]:
t_41 = torch.chunk(t_4, 2, 0)
t_41

(tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7],
           [  8,   9,  10,  11,  12,  13,  14,  15],
           [ 16,  17,  18,  19,  20,  21,  22,  23],
           [ 24,  25,  26,  27,  28,  29,  30,  31],
           [ 32,  33,  34,  35,  36,  37,  38,  39],
           [ 40,  41,  42,  43,  44,  45,  46,  47]],
 
          [[ 48,  49,  50,  51,  52,  53,  54,  55],
           [ 56,  57,  58,  59,  60,  61,  62,  63],
           [ 64,  65,  66,  67,  68,  69,  70,  71],
           [ 72,  73,  74,  75,  76,  77,  78,  79],
           [ 80,  81,  82,  83,  84,  85,  86,  87],
           [ 88,  89,  90,  91,  92,  93,  94,  95]],
 
          [[ 96,  97,  98,  99, 100, 101, 102, 103],
           [104, 105, 106, 107, 108, 109, 110, 111],
           [112, 113, 114, 115, 116, 117, 118, 119],
           [120, 121, 122, 123, 124, 125, 126, 127],
           [128, 129, 130, 131, 132, 133, 134, 135],
           [136, 137, 138, 139, 140, 141, 142, 143]]],
 
 
         [[[144, 145, 146, 147, 14

In [42]:
t_42 = torch.chunk(t_4, 2, 1)
t_42

(tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7],
           [  8,   9,  10,  11,  12,  13,  14,  15],
           [ 16,  17,  18,  19,  20,  21,  22,  23],
           [ 24,  25,  26,  27,  28,  29,  30,  31],
           [ 32,  33,  34,  35,  36,  37,  38,  39],
           [ 40,  41,  42,  43,  44,  45,  46,  47]],
 
          [[ 48,  49,  50,  51,  52,  53,  54,  55],
           [ 56,  57,  58,  59,  60,  61,  62,  63],
           [ 64,  65,  66,  67,  68,  69,  70,  71],
           [ 72,  73,  74,  75,  76,  77,  78,  79],
           [ 80,  81,  82,  83,  84,  85,  86,  87],
           [ 88,  89,  90,  91,  92,  93,  94,  95]]],
 
 
         [[[144, 145, 146, 147, 148, 149, 150, 151],
           [152, 153, 154, 155, 156, 157, 158, 159],
           [160, 161, 162, 163, 164, 165, 166, 167],
           [168, 169, 170, 171, 172, 173, 174, 175],
           [176, 177, 178, 179, 180, 181, 182, 183],
           [184, 185, 186, 187, 188, 189, 190, 191]],
 
          [[192, 193, 194, 195, 19

In [43]:
t_43 = torch.chunk(t_4, 3, 2)
t_43

(tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7],
           [  8,   9,  10,  11,  12,  13,  14,  15]],
 
          [[ 48,  49,  50,  51,  52,  53,  54,  55],
           [ 56,  57,  58,  59,  60,  61,  62,  63]],
 
          [[ 96,  97,  98,  99, 100, 101, 102, 103],
           [104, 105, 106, 107, 108, 109, 110, 111]]],
 
 
         [[[144, 145, 146, 147, 148, 149, 150, 151],
           [152, 153, 154, 155, 156, 157, 158, 159]],
 
          [[192, 193, 194, 195, 196, 197, 198, 199],
           [200, 201, 202, 203, 204, 205, 206, 207]],
 
          [[240, 241, 242, 243, 244, 245, 246, 247],
           [248, 249, 250, 251, 252, 253, 254, 255]]],
 
 
         [[[288, 289, 290, 291, 292, 293, 294, 295],
           [296, 297, 298, 299, 300, 301, 302, 303]],
 
          [[336, 337, 338, 339, 340, 341, 342, 343],
           [344, 345, 346, 347, 348, 349, 350, 351]],
 
          [[384, 385, 386, 387, 388, 389, 390, 391],
           [392, 393, 394, 395, 396, 397, 398, 399]]],
 
 
         [

In [44]:
t_43 = torch.chunk(t_4, 3, 3)
t_43

(tensor([[[[  0,   1,   2],
           [  8,   9,  10],
           [ 16,  17,  18],
           [ 24,  25,  26],
           [ 32,  33,  34],
           [ 40,  41,  42]],
 
          [[ 48,  49,  50],
           [ 56,  57,  58],
           [ 64,  65,  66],
           [ 72,  73,  74],
           [ 80,  81,  82],
           [ 88,  89,  90]],
 
          [[ 96,  97,  98],
           [104, 105, 106],
           [112, 113, 114],
           [120, 121, 122],
           [128, 129, 130],
           [136, 137, 138]]],
 
 
         [[[144, 145, 146],
           [152, 153, 154],
           [160, 161, 162],
           [168, 169, 170],
           [176, 177, 178],
           [184, 185, 186]],
 
          [[192, 193, 194],
           [200, 201, 202],
           [208, 209, 210],
           [216, 217, 218],
           [224, 225, 226],
           [232, 233, 234]],
 
          [[240, 241, 242],
           [248, 249, 250],
           [256, 257, 258],
           [264, 265, 266],
           [272, 273, 274],
  