### torch.multinomial方法解析

In [1]:
import torch

#### input tensor为vector

In [4]:
input_tensor = torch.tensor([1, 8, 4, 6, 3],dtype=torch.float)
input_tensor

tensor([1., 8., 4., 6., 3.])

In [5]:
num_samples = 2
output_tensor = torch.multinomial(input_tensor, num_samples)
output_tensor

tensor([3, 1])

#### input tensor为tensor

In [10]:
input_tensor = torch.rand((5, 8))
input_tensor, input_tensor.shape

(tensor([[0.1574, 0.5496, 0.0155, 0.6744, 0.4049, 0.4269, 0.6125, 0.5890],
         [0.4629, 0.9088, 0.0980, 0.4133, 0.4441, 0.1809, 0.0920, 0.7344],
         [0.7481, 0.4842, 0.8619, 0.6378, 0.0855, 0.4246, 0.6105, 0.0809],
         [0.9039, 0.4378, 0.0284, 0.7569, 0.8727, 0.7914, 0.9640, 0.4335],
         [0.2522, 0.6605, 0.8084, 0.3068, 0.6353, 0.4429, 0.8217, 0.5823]]),
 torch.Size([5, 8]))

In [9]:
num_samples = 3
output_tensor = torch.multinomial(input_tensor, num_samples)
output_tensor, output_tensor.shape

(tensor([[6, 4, 3],
         [7, 0, 6],
         [1, 5, 4],
         [5, 7, 1],
         [3, 2, 7]]),
 torch.Size([5, 3]))

#### replacement=True

In [25]:
input_tensor = torch.tensor([0, 4, 6, 0],dtype=torch.float)
input_tensor, input_tensor.shape

(tensor([0., 4., 6., 0.]), torch.Size([4]))

In [27]:
num_samples = 5
torch.multinomial(input_tensor, num_samples)

RuntimeError: cannot sample n_sample > prob_dist.size(-1) samples without replacement

In [28]:
num_samples = 5
torch.multinomial(input_tensor, num_samples, replacement=True)

tensor([1, 2, 1, 2, 2])