## torch.bincount()

### 1-d

In [ ]:
import torch

In [ ]:
# create a tensor, length is 5
t = torch.randint(0,10,(5,))
t

tensor([2, 6, 5, 1, 5])

In [ ]:
count = torch.bincount(t)
count

tensor([0, 1, 1, 0, 0, 2, 1])

### Multi-d
- 如果是多维tensor, 在计数之前, 需进行flatten操作

In [9]:
t1 = torch.randint(0,10,(3,3))
t1

tensor([[0, 4, 3],
        [2, 1, 9],
        [8, 5, 8]])

In [13]:
t1 = t1.flatten()
count_t1 = torch.bincount(t1)
count_t1

tensor([1, 1, 1, 1, 1, 1, 0, 0, 2, 1])